# Generated by Django 5.2.4 on 2025-07-28 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_alter_taskmodel_assigned_to_alter_taskmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
