# Generated by Django 5.2.4 on 2025-07-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_alter_taskmodel_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='assigned_to',
        ),
    ]
